### ISSUE TITLE
Mistral Home Directory

### ISSUE THREAD

**Issue by fultonj** [fultonj/tripleo-ceph-ansible#12]
Mistral's home directory is set to /home/mistral [1], as per the RDO package I suspect, but that directory does not exist. It should be set to an existing directory and doing so fixes a problem with Mistral ansible actions. 

[1] 
(undercloud) [stack@undercloud ceph-ansible]$ grep mistral /etc/passwd
mistral:x:980:977:Mistral Daemons:/home/mistral:/sbin/nologin
(undercloud) [stack@undercloud ceph-ansible]$

**Comment by fultonj** [comment]
While running this playbook

 https://github.com/ceph/ceph-ansible/blob/master/site.yml.sample#L21-L23

I get:
```
PLAY [mons,agents,osds,mdss,rgws,nfss,restapis,rbdmirrors,clients,iscsigws,mgrs] ***\
\
TASK [check for python2] *******************************************************\
fatal: [192.168.24.12]: FAILED! => {"failed": true, "msg": "Unable to create local directories(/home/mistral/.ansible/cp): [Errno 13] Permission denied: \\'/home/mistral\\'"}\
...ignoring\
fatal: []: FAILED! => {"failed": true, "msg": "Unable to create local directories(/home/mistral/.ansible/cp): [Errno 13] Permission denied: \\'/home/mistral\\'"}\
...ignoring\
fatal: [192.168.24.15]: FAILED! => {"failed": true, "msg": "Unable to create local directories(/home/mistral/.ansible/cp): [Errno 13] Permission denied: \\'/home/mistral\\'"}\
...ignoring\
\
TASK [install python2 for Debian based systems] **********
```

My playbook is being run the by mistral-user who shouldn't have a /home/mistral directory. 

I originally was getting this error: 
```
Stderr: u'Traceback (most recent call last):\
  File "/usr/bin/ansible-playbook", line 43, in <module>\
    import ansible.constants as C\
  File "/usr/lib/python2.7/site-packages/ansible/constants.py", line 161, in <module>\
    DEFAULT_LOCAL_TMP         = get_config(p, DEFAULTS, \\'local_tmp\\',        \\'ANSIBLE_LOCAL_TEMP\\',      \\'~/.ansible/tmp\\', istmppath=True)\
  File "/usr/lib/python2.7/site-packages/ansible/constants.py", line 81, in get_config\
    makedirs_safe(value, 0o700)\
  File "/usr/lib/python2.7/site-packages/ansible/utils/path.py", line 70, in makedirs_safe\
    raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e)))\
ansible.errors.AnsibleError: Unable to create local directories(/home/mistral/.ansible/tmp): [Errno 13] Permission denied: \\'/home/mistral\\'\
```
But I worked around it by adding "local_tmp=/tmp/.ansible/tmp" to /etc/ansible/ansible.cfg 
and verified that /tmp/.ansible/tmp was creatd on my system after doing so.

However, there are parts of Ansible that use whatever $HOME expands to. If I simply create set what that home directory is in /etc/password to a directory that mistral can write to, then suddenly I don't have this issue and my Mistral worfklow succeeds. 

https://review.openstack.org/#/c/469644/8

E.g. It worked with the following: 

(undercloud) [stack@undercloud tripleo-ceph-ansible]$ grep mistral /etc/passwd
mistral:x:980:977:Mistral Daemons:/tmp/mistral:/sbin/nologin
(undercloud) [stack@undercloud tripleo-ceph-ansible]$

**Comment by fultonj** [comment]
Here's another idea
```
(undercloud) [stack@undercloud tripleo-ceph-ansible]$ echo $HOME; HOME=/tmp/foo; ansible all -i 192.168.24.15, -u heat-admin -m ping ; HOME=/home/stack
/home/stack
192.168.24.15 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
(undercloud) [stack@undercloud tripleo-ceph-ansible]$ ls -la /tmp/foo/
total 256
drwxrwxr-x.    3 stack stack     22 Jun  9 15:21 .
drwxrwxrwt. 5585 root  root  184320 Jun  9 15:21 ..
drwx------.    4 stack stack     27 Jun  9 15:21 .ansible
(undercloud) [stack@undercloud tripleo-ceph-ansible]$ 
```

**Comment by fultonj** [comment]
Talked to d0ugal and rbrady suggestion:
Have the RDO package modified by submitting a change to the specfile in the distgit. 

The following should be chantged:
https://github.com/rdo-packages/mistral-distgit/blob/rpm-master/openstack-mistral.spec#L281-L289

To make it more like:
https://github.com/rdo-packages/heat-distgit/blob/rpm-master/openstack-heat.spec#L324

Next step: connect this issue to and actual RDO request

**Comment by fultonj** [comment]
flapper87 thinks this may be solved by a patch to the code introduced by  https://review.openstack.org/#/c/470021/ after it merges. 

The patch would set $HOME temporarily for the execution of the playbook. The Ansible Environment might help: https://docs.ansible.com/ansible/playbooks_environment.html

**Comment by fultonj** [comment]
I am going to wait for flaper87's change . Until then I have the following which doesn't seem to require any environmental changes: 
 https://github.com/fultonj/mistral-ansible-actions/blob/master/mistral_ansible_actions.py#L294

Aside from these: 
 https://github.com/fultonj/tripleo-ceph-ansible/blob/master/init.sh#L100-L104

**Comment by fultonj** [comment]
Waiting on: 

https://review.openstack.org/#/c/473585/
https://review.openstack.org/#/c/473587/
https://review.openstack.org/#/c/473586/

**Comment by fultonj** [comment]
https://review.openstack.org/#/c/473585 merged. 

waiting on: 
https://review.openstack.org/#/c/473587/
https://review.openstack.org/#/c/473586/

**Comment by fultonj** [comment]
Tested the following and they work. Waiting for them to merge:

https://review.openstack.org/#/c/473587/
https://review.openstack.org/#/c/473586/
https://review.openstack.org/#/c/474976/

**Comment by fultonj** [comment]
These have merged
